export interface UserProfile {
  id: string;
  name: string;
  initials: string;
  role: 'student' | 'tutor';
  campus: 'Farnham' | 'Epsom' | 'Canterbury' | 'Rochester';
  course: string;
  bio: string;
  skills: string[];
  interests: string[];
  available: boolean;
  portfolioUrl?: string;
  githubUrl?: string;
  behanceUrl?: string;
  avatarColor: string;
  yearOfStudy?: string;
  projectCount: number;
  connectionCount: number;
}

export const ALL_USERS: UserProfile[] = [
  {
    id: 'user-001',
    name: 'Alex',
    initials: 'PK',
    role: 'student',
    campus: 'Farnham',
    course: 'Creative Computing',
    bio: 'Final year Creative Computing student obsessed with WebXR, generative art, and making the web feel alive. Looking for collaborators on AR/XR briefs.',
    skills: ['React', 'Three.js', 'WebGL', 'JavaScript', 'Creative Coding', 'UI/UX Design'],
    interests: ['AR/XR', 'Generative Art', 'Interactive Installations'],
    available: true,
    portfolioUrl: 'https://Alex.xyz',
    githubUrl: 'https://github.com/Alex',
    avatarColor: '#6C47FF',
    yearOfStudy: 'Year 3',
    projectCount: 4,
    connectionCount: 23,
  },
  {
    id: 'user-002',
    name: 'Marcus Osei',
    initials: 'MO',
    role: 'student',
    campus: 'Epsom',
    course: 'Games Design',
    bio: 'Games designer and Unity developer with a focus on narrative-driven experiences. Currently building a horror puzzle game for my final project.',
    skills: ['Unity', 'C#', 'Game Development', 'Unreal Engine', 'Storyboarding', '3D Modelling'],
    interests: ['Narrative Games', 'Horror', 'Level Design', 'Sound Design'],
    available: true,
    githubUrl: 'https://github.com/marcosei',
    avatarColor: '#FF6B6B',
    yearOfStudy: 'Year 3',
    projectCount: 6,
    connectionCount: 31,
  },
  {
    id: 'user-003',
    name: 'John',
    initials: 'LH',
    role: 'student',
    campus: 'Canterbury',
    course: 'Animation',
    bio: '2D/3D animator specialising in character animation and motion graphics. Love bringing characters to life with personality and weight.',
    skills: ['After Effects', 'Blender', 'Character Design', 'Storyboarding', 'Lottie', 'Cinema 4D'],
    interests: ['Character Animation', 'Motion Graphics', 'Short Films'],
    available: false,
    portfolioUrl: 'https://John.art',
    behanceUrl: 'https://behance.net/John',
    avatarColor: '#F59E0B',
    yearOfStudy: 'Year 2',
    projectCount: 3,
    connectionCount: 17,
  },
  {
    id: 'user-004',
    name: 'Tomas',
    initials: 'TR',
    role: 'student',
    campus: 'Farnham',
    course: 'UI/UX Design',
    bio: 'UX researcher and product designer. I believe great design starts with deep empathy and solid research. Currently exploring accessibility in creative tools.',
    skills: ['Figma', 'UI/UX Design', 'User Research', 'Prototyping', 'Accessibility', 'Design Systems'],
    interests: ['Accessible Design', 'Design Systems', 'Service Design'],
    available: true,
    portfolioUrl: 'https://tomas.design',
    behanceUrl: 'https://behance.net/tomas',
    avatarColor: '#22C55E',
    yearOfStudy: 'Year 3',
    projectCount: 5,
    connectionCount: 28,
  },
  {
    id: 'user-005',
    name: 'Dr. Yuki Tanaka',
    initials: 'YT',
    role: 'tutor',
    campus: 'Canterbury',
    course: 'Animation',
    bio: 'Senior lecturer in Animation with 12 years of industry experience at Aardman and Nexus Studios. Research interests in AI-assisted animation pipelines.',
    skills: ['Animation', 'After Effects', 'Blender', 'Teaching', 'Research', 'Motion Design'],
    interests: ['AI in Animation', 'Stop Motion', 'Experimental Film'],
    available: true,
    avatarColor: '#0EA5E9',
    projectCount: 12,
    connectionCount: 87,
  },
  {
    id: 'user-006',
    name: 'Kris',
    initials: 'AB',
    role: 'student',
    campus: 'Epsom',
    course: 'Graphic Design',
    bio: 'Graphic designer with a love for editorial layouts, brand identity, and experimental typography. Seeking collaborators for a cross-discipline zine project.',
    skills: ['Graphic Design', 'Typography', 'Illustrator', 'InDesign', 'Brand Identity', 'Print Design'],
    interests: ['Editorial Design', 'Zines', 'Type Design', 'Risograph Printing'],
    available: true,
    portfolioUrl: 'https://kris.ie',
    behanceUrl: 'https://behance.net/kris',
    avatarColor: '#EC4899',
    yearOfStudy: 'Year 2',
    projectCount: 4,
    connectionCount: 19,
  },
  {
    id: 'user-007',
    name: 'Kwame Asante',
    initials: 'KA',
    role: 'student',
    campus: 'Rochester',
    course: 'Film & TV Production',
    bio: 'Cinematographer and director with a documentary focus. Looking for animators, sound designers, and composers to collaborate on a short film about creative communities.',
    skills: ['Premiere Pro', 'DaVinci Resolve', 'Cinematography', 'Directing', 'Colour Grading', 'Documentary'],
    interests: ['Documentary Film', 'Social Impact', 'Experimental Video'],
    available: true,
    portfolioUrl: 'https://kwameasante.film',
    avatarColor: '#8B5CF6',
    yearOfStudy: 'Year 3',
    projectCount: 7,
    connectionCount: 42,
  },
  {
    id: 'user-008',
    name: 'Saoirse Murphy',
    initials: 'SM',
    role: 'student',
    campus: 'Farnham',
    course: 'Photography',
    bio: 'Documentary photographer exploring identity, diaspora, and belonging. Interested in combining still photography with digital installation work.',
    skills: ['Photography', 'Lightroom', 'Photoshop', 'Video Production', 'Digital Installation', 'Darkroom'],
    interests: ['Documentary Photography', 'Identity', 'Installation Art'],
    available: false,
    portfolioUrl: 'https://saoirsemurphy.co.uk',
    behanceUrl: 'https://behance.net/saoirsemurphy',
    avatarColor: '#14B8A6',
    yearOfStudy: 'Year 3',
    projectCount: 5,
    connectionCount: 26,
  },
  {
    id: 'user-009',
    name: 'Prof. David Okafor',
    initials: 'DO',
    role: 'tutor',
    campus: 'Epsom',
    course: 'Games Design',
    bio: 'Programme leader for Games Design. Former lead designer at Rocksteady Studios. Specialises in game mechanics, player psychology, and emergent narrative.',
    skills: ['Game Development', 'Unity', 'Unreal Engine', 'Game Design Theory', 'Prototyping', 'Teaching'],
    interests: ['Emergent Narrative', 'Player Psychology', 'Accessibility in Games'],
    available: true,
    avatarColor: '#F97316',
    projectCount: 18,
    connectionCount: 124,
  },
  {
    id: 'user-010',
    name: 'Niamh Fitzgerald',
    initials: 'NF',
    role: 'student',
    campus: 'Canterbury',
    course: 'Illustration',
    bio: 'Illustrator with a love for folklore, botanical illustration, and hand-lettering. Looking for writers and game designers for a narrative illustration project.',
    skills: ['Illustration', 'Procreate', 'Photoshop', 'Hand-lettering', 'Character Design', 'Concept Art'],
    interests: ['Folk Art', 'Narrative Illustration', 'Book Cover Design'],
    available: true,
    portfolioUrl: 'https://niamhfitz.art',
    behanceUrl: 'https://behance.net/niamhfitz',
    avatarColor: '#A855F7',
    yearOfStudy: 'Year 2',
    projectCount: 3,
    connectionCount: 14,
  },
  {
    id: 'user-011',
    name: 'Reza Shirazi',
    initials: 'RS',
    role: 'student',
    campus: 'Farnham',
    course: 'Creative Computing',
    bio: 'Creative technologist working at the intersection of code and sound. Building a live-coding performance tool using Web Audio API and Tone.js.',
    skills: ['JavaScript', 'Python', 'Web Audio', 'Tone.js', 'Creative Coding', 'Live Coding'],
    interests: ['Algorithmic Music', 'Live Performance', 'Sound Art', 'Livecoding'],
    available: true,
    githubUrl: 'https://github.com/rezashirazi',
    portfolioUrl: 'https://reza.codes',
    avatarColor: '#06B6D4',
    yearOfStudy: 'Year 2',
    projectCount: 2,
    connectionCount: 11,
  },
  {
    id: 'user-012',
    name: 'Ingrid Larsson',
    initials: 'IL',
    role: 'student',
    campus: 'Epsom',
    course: 'Fashion Design',
    bio: 'Fashion designer exploring sustainable textiles and digital fashion. Keen to collaborate with technologists on AR try-on experiences and digital garments.',
    skills: ['Fashion Design', 'Pattern Cutting', 'Illustrator', 'CLO3D', 'Textile Design', 'Sustainability'],
    interests: ['Digital Fashion', 'Sustainable Design', 'AR Try-On', 'Slow Fashion'],
    available: false,
    portfolioUrl: 'https://ingridlarsson.se',
    behanceUrl: 'https://behance.net/ingridlarsson',
    avatarColor: '#D946EF',
    yearOfStudy: 'Year 3',
    projectCount: 4,
    connectionCount: 22,
  },
];

export const ALL_SKILLS = [
  'After Effects', 'Blender', 'C#', 'Character Design', 'Cinema 4D',
  'Creative Coding', 'CSS', 'Figma', 'Film Editing', 'Game Development',
  'Graphic Design', 'HTML', 'Illustration', 'JavaScript', 'Motion Graphics',
  'Photography', 'Premiere Pro', 'Procreate', 'Python', 'React',
  'Storyboarding', 'Three.js', 'TypeScript', 'UI/UX Design', 'Unity',
  'Unreal Engine', 'Web Audio', 'WebGL',
];

export const COURSES = [
  'Animation', 'Architecture', 'Creative Computing', 'Fashion Design',
  'Film & TV Production', 'Fine Art', 'Games Design', 'Graphic Design',
  'Illustration', 'Photography', 'UI/UX Design',
];

export const MOCK_PROJECTS = [
  { id: 'proj-001', title: 'Immersive Campus Wayfinding — AR Prototype' },
  { id: 'proj-002', title: 'Generative Poster Series — Live Brief' },
  { id: 'proj-003', title: 'Short Documentary — Creative Communities' },
];